/**
 * Demo household: The Pink Palace.
 *
 * Dates are generated relative to `now` so the board always looks alive
 * (something overdue, something due tonight, a few coming up, a few done).
 * Replace createSeedState with a database fetch when a backend exists.
 */
import { HOUR, DAY, MINUTE } from "./time";
import type { ActivityEvent, Chore, HouseholdState, Roommate } from "./types";

export const STATE_VERSION = 1;

const ROOMMATES: Roommate[] = [
  {
    id: "krystiana",
    name: "Krystiana",
    accent: "lilac",
    emoji: "🌸",
    status: "matcha-powered today 🍵",
    streak: 6,
    history: { completed: 41, onTime: 38 },
  },
  {
    id: "ellie",
    name: "Ellie",
    accent: "coral",
    emoji: "🍓",
    status: "exam week, be nice 📚",
    streak: 2,
    history: { completed: 33, onTime: 27 },
  },
  {
    id: "katie",
    name: "Katie",
    accent: "mint",
    emoji: "🌿",
    status: "plant mom era 🪴",
    streak: 9,
    history: { completed: 48, onTime: 46 },
  },
  {
    id: "emery",
    name: "Emery",
    accent: "butter",
    emoji: "🌼",
    status: "closing shifts all week 🌙",
    streak: 4,
    history: { completed: 29, onTime: 25 },
  },
];

export function createSeedState(now: Date = new Date()): HouseholdState {
  /** A date `days` from today at hh:mm local time. */
  const at = (days: number, hours: number, minutes = 0) => {
    const d = new Date(now);
    d.setDate(d.getDate() + days);
    d.setHours(hours, minutes, 0, 0);
    return d.toISOString();
  };
  const ago = (ms: number) => new Date(now.getTime() - ms).toISOString();
  /** Later today at `hour` if still possible, otherwise ~an hour from now. */
  const laterToday = (hour: number) =>
    now.getHours() < hour - 1 ? at(0, hour) : new Date(now.getTime() + 50 * MINUTE).toISOString();

  const base = { createdAt: ago(14 * DAY), status: "open" as const };

  const chores: Chore[] = [
    // --- Running late -------------------------------------------------------
    {
      ...base,
      id: "chore_trash",
      seriesId: "series_trash",
      title: "Take out the trash",
      description: "Kitchen + bathroom bins. Pickup is Thursday morning!",
      category: "trash",
      assigneeId: "ellie",
      dueAt: at(-1, 20),
      recurrence: "weekly",
      rotate: true,
      points: 1,
      createdBy: "katie",
    },
    {
      ...base,
      id: "chore_dishwasher",
      seriesId: "series_dishwasher",
      title: "Unload dishwasher",
      category: "kitchen",
      assigneeId: "emery",
      // Earlier today on the hour (or late last night just after midnight).
      dueAt: now.getHours() >= 2 ? at(0, now.getHours() - 1) : at(-1, 22),
      recurrence: "daily",
      rotate: true,
      points: 1,
      createdBy: "krystiana",
    },
    // --- Today --------------------------------------------------------------
    {
      ...base,
      id: "chore_counters",
      seriesId: "series_counters",
      title: "Wipe kitchen counters",
      description: "The good spray is under the sink 🍋",
      category: "kitchen",
      assigneeId: "krystiana",
      dueAt: laterToday(21),
      recurrence: "daily",
      rotate: false,
      points: 1,
      createdBy: "krystiana",
    },
    {
      ...base,
      id: "chore_plants",
      seriesId: "series_plants",
      title: "Water plants",
      description: "Not the snake plant — she likes to be left alone.",
      category: "plants",
      assigneeId: "katie",
      dueAt: laterToday(19),
      recurrence: "weekly",
      rotate: false,
      points: 1,
      createdBy: "katie",
    },
    {
      ...base,
      id: "chore_vacuum",
      seriesId: "series_vacuum",
      title: "Vacuum living room",
      category: "living",
      assigneeId: "krystiana",
      dueAt: laterToday(22),
      recurrence: "weekly",
      rotate: true,
      points: 2,
      createdBy: "emery",
    },
    // --- Coming up ----------------------------------------------------------
    {
      ...base,
      id: "chore_bathroom",
      seriesId: "series_bathroom",
      title: "Clean bathroom",
      description: "Sink, mirror, toilet, and a quick mop.",
      category: "bathroom",
      assigneeId: "katie",
      dueAt: at(2, 11),
      recurrence: "weekly",
      rotate: true,
      points: 3,
      createdBy: "katie",
    },
    {
      ...base,
      id: "chore_tp",
      seriesId: "series_tp",
      title: "Restock toilet paper",
      category: "supplies",
      assigneeId: "emery",
      dueAt: at(3, 18),
      recurrence: "monthly",
      rotate: true,
      points: 1,
      createdBy: "ellie",
    },
    {
      ...base,
      id: "chore_towels",
      seriesId: "series_towels",
      title: "Wash shared towels",
      category: "laundry",
      assigneeId: "ellie",
      dueAt: at(4, 12),
      recurrence: "biweekly",
      rotate: true,
      points: 2,
      createdBy: "krystiana",
    },
    {
      ...base,
      id: "chore_fridge",
      seriesId: "series_fridge",
      title: "Deep clean the fridge",
      description: "Toss anything mysterious. No judgment 🫡",
      category: "kitchen",
      assigneeId: "emery",
      dueAt: at(6, 17),
      recurrence: "monthly",
      rotate: true,
      points: 3,
      createdBy: "ellie",
      createdAt: ago(DAY + 3 * HOUR),
    },
    // --- Done ---------------------------------------------------------------
    {
      ...base,
      id: "chore_soap_done",
      seriesId: "series_soap",
      title: "Restock dish soap",
      category: "supplies",
      assigneeId: "katie",
      dueAt: at(0, 23, 30),
      recurrence: "once",
      rotate: false,
      points: 1,
      createdBy: "ellie",
      status: "done",
      completedAt: ago(2 * HOUR),
      completedBy: "katie",
    },
    {
      ...base,
      id: "chore_dishwasher_done",
      seriesId: "series_dishwasher",
      title: "Unload dishwasher",
      category: "kitchen",
      assigneeId: "katie",
      dueAt: ago(DAY + 90 * MINUTE),
      recurrence: "daily",
      rotate: true,
      points: 1,
      createdBy: "krystiana",
      status: "done",
      completedAt: ago(DAY + 3 * HOUR),
      completedBy: "katie",
    },
    {
      ...base,
      id: "chore_bathroom_done",
      seriesId: "series_bathroom",
      title: "Clean bathroom",
      category: "bathroom",
      assigneeId: "ellie",
      dueAt: at(-5, 11),
      recurrence: "weekly",
      rotate: true,
      points: 3,
      createdBy: "katie",
      status: "done",
      completedAt: at(-5, 10, 15),
      completedBy: "ellie",
    },
    {
      ...base,
      id: "chore_trash_done",
      seriesId: "series_trash",
      title: "Take out the trash",
      category: "trash",
      assigneeId: "krystiana",
      dueAt: at(-8, 20),
      recurrence: "weekly",
      rotate: true,
      points: 1,
      createdBy: "katie",
      status: "done",
      completedAt: at(-8, 18, 40),
      completedBy: "krystiana",
    },
  ];

  const activity: ActivityEvent[] = [
    {
      id: "evt_soap",
      type: "completed",
      at: ago(2 * HOUR),
      actorId: "katie",
      choreId: "chore_soap_done",
      choreTitle: "Restock dish soap",
      assigneeId: "katie",
      reactions: { "🙌": ["krystiana", "ellie"] },
    },
    {
      id: "evt_nudge_trash",
      type: "nudged",
      at: ago(3 * HOUR),
      actorId: "katie",
      targetId: "ellie",
      choreId: "chore_trash",
      choreTitle: "Take out the trash",
      tone: "funny",
      message: "the trash bags are forming a union 😭 pls free them",
      reactions: { "😂": ["krystiana", "emery"] },
    },
    {
      id: "evt_fridge_created",
      type: "created",
      at: ago(DAY + 3 * HOUR),
      actorId: "ellie",
      choreId: "chore_fridge",
      choreTitle: "Deep clean the fridge",
      assigneeId: "emery",
      reactions: {},
    },
    {
      id: "evt_dish_rotated",
      type: "rotated",
      at: ago(DAY + 3 * HOUR - 1),
      choreTitle: "Unload dishwasher",
      toId: "emery",
      reactions: {},
    },
    {
      id: "evt_dish_done",
      type: "completed",
      at: ago(DAY + 3 * HOUR),
      actorId: "katie",
      choreId: "chore_dishwasher_done",
      choreTitle: "Unload dishwasher",
      assigneeId: "katie",
      reactions: {},
    },
    {
      id: "evt_bathroom_done",
      type: "completed",
      at: at(-5, 10, 15),
      actorId: "ellie",
      choreId: "chore_bathroom_done",
      choreTitle: "Clean bathroom",
      assigneeId: "ellie",
      reactions: { "✨": ["katie", "krystiana", "emery"] },
    },
    {
      id: "evt_trash_rotated",
      type: "rotated",
      at: at(-8, 18, 41),
      choreTitle: "Take out the trash",
      toId: "ellie",
      reactions: {},
    },
    {
      id: "evt_trash_done",
      type: "completed",
      at: at(-8, 18, 40),
      actorId: "krystiana",
      choreId: "chore_trash_done",
      choreTitle: "Take out the trash",
      assigneeId: "krystiana",
      reactions: { "💕": ["ellie"] },
    },
  ];

  return {
    version: STATE_VERSION,
    household: {
      id: "pink-palace",
      name: "The Pink Palace",
      emoji: "🏡",
      inviteCode: "PINK-4821",
      memberIds: ROOMMATES.map((r) => r.id),
    },
    roommates: ROOMMATES,
    chores,
    activity,
    currentUserId: "krystiana",
  };
}
